//! Board definition: 立创实战派 ESP32-S3 (LiChuang SZP)
//!
//! LCD: 320x240 ST7789 SPI
//!   MOSI=40, CLK=41, DC=39, Backlight=42
//!   CS via PCA9557 GPIO expander (I2C addr 0x19, pin 0)

const modules = @import("idf").sdkconfig_components;
const partition = @import("idf").partition;

const large_app_partition_table: partition.Table = .{
    .offset = 0x8000,
    .entries = &.{
        .{ .name = "nvs", .kind = .data, .subtype = .nvs, .offset = 0x9000, .size = 0x6000 },
        .{ .name = "phy_init", .kind = .data, .subtype = .phy, .offset = 0xF000, .size = 0x1000 },
        .{ .name = "factory", .kind = .app, .subtype = .factory, .offset = 0x10000, .size = 8 * 1024 * 1024 },
        .{
            .name = "font_store",
            .kind = .data,
            .subtype = .spiffs,
            .size = 3 * 1024 * 1024,
            .data = partition.data.spiffs("../../firmware/106-lcd-hello-world/data"),
        },
    },
};

pub const config = .{
    .core = modules.esp_system_config.Config.withDefaultConfig(.{
        .main_task_stack_size = 16384,
    }),
    .esp_misc = modules.esp_misc_config.Config.withDefaultConfig(.{
        .esp_main_task_stack_size = 16384,
    }),
    .freertos = modules.freertos_config.Config.default,
    .app_metadata = modules.app_metadata_config.Config.default,
    .app_trace = modules.app_trace_config.Config.default,
    .bootloader = modules.bootloader_config.Config.default,
    .bt = modules.bt_config.Config.default,
    .console = modules.console_config.Config.default,
    .efuse = modules.efuse_config.Config.default,
    .esp_adc = modules.esp_adc_config.Config.default,
    .esp_coex = modules.esp_coex_config.Config.default,
    .esp_driver_gdma = modules.esp_driver_gdma_config.Config.default,
    .esp_driver_gpio = modules.esp_driver_gpio_config.Config.default,
    .esp_driver_gptimer = modules.esp_driver_gptimer_config.Config.default,
    .esp_driver_i2c = modules.esp_driver_i2c_config.Config.default,
    .esp_driver_i2s = modules.esp_driver_i2s_config.Config.default,
    .esp_driver_ledc = modules.esp_driver_ledc_config.Config.default,
    .esp_driver_mcpwm = modules.esp_driver_mcpwm_config.Config.default,
    .esp_driver_pcnt = modules.esp_driver_pcnt_config.Config.default,
    .esp_driver_rmt = modules.esp_driver_rmt_config.Config.default,
    .esp_driver_sdm = modules.esp_driver_sdm_config.Config.default,
    .esp_driver_spi = modules.esp_driver_spi_config.Config.default,
    .esp_driver_touch_sens = modules.esp_driver_touch_sens_config.Config.default,
    .esp_driver_tsens = modules.esp_driver_tsens_config.Config.default,
    .esp_driver_twai = modules.esp_driver_twai_config.Config.default,
    .esp_driver_uart = modules.esp_driver_uart_config.Config.default,
    .esp_eth = modules.esp_eth_config.Config.default,
    .esp_event = modules.esp_event_config.Config.default,
    .esp_gdbstub = modules.esp_gdbstub_config.Config.default,
    .esp_http_client = modules.esp_http_client_config.Config.default,
    .esp_http_server = modules.esp_http_server_config.Config.default,
    .esp_https_ota = modules.esp_https_ota_config.Config.default,
    .esp_https_server = modules.esp_https_server_config.Config.default,
    .esp_hw_support = modules.esp_hw_support_config.Config.default,
    .esp_lcd = modules.esp_lcd_config.Config.default,
    .esp_mm = modules.esp_mm_config.Config.default,
    .esp_netif = modules.esp_netif_config.Config.default,
    .esp_phy = modules.esp_phy_config.Config.default,
    .esp_pm = modules.esp_pm_config.Config.default,
    .esp_psram = modules.esp_psram_config.Config.withDefaultConfig(.{
        .spiram = true,
        .spiram_mode_oct = true,
        .spiram_speed_80m = true,
    }),
    .esp_security = modules.esp_security_config.Config.default,
    .esp_timer = modules.esp_timer_config.Config.default,
    .esp_wifi = modules.esp_wifi_config.Config.default,
    .espcoredump = modules.espcoredump_config.Config.default,
    .esptool_py = modules.esptool_py_config.Config.withDefaultConfig(.{
        .esptoolpy_flashsize = "16MB",
        .esptoolpy_flashsize_16mb = true,
        .esptoolpy_flashsize_2mb = false,
    }),
    .fatfs = modules.fatfs_config.Config.default,
    .hal = modules.hal_config.Config.default,
    .heap = modules.heap_config.Config.default,
    .idf_build_system = modules.idf_build_system_config.Config.default,
    .log = modules.log_config.Config.default,
    .lwip = modules.lwip_config.Config.default,
    .mbedtls = modules.mbedtls_config.Config.default,
    .mqtt = modules.mqtt_config.Config.default,
    .newlib = modules.newlib_config.Config.default,
    .nvs_flash = modules.nvs_flash_config.Config.default,
    .openthread = modules.openthread_config.Config.default,
    .partition_table_cfg = modules.partition_table_config.Config.default,
    .pthread = modules.pthread_config.Config.default,
    .soc = modules.soc_config.Config.default,
    .spi_flash = modules.spi_flash_config.Config.default,
    .spiffs = modules.spiffs_config.Config.default,
    .target_soc = modules.target_soc_config.Config.withDefaultConfig(.{
        .esp32s3_spiram_support = true,
    }),
    .tcp_transport = modules.tcp_transport_config.Config.default,
    .toolchain = modules.toolchain_config.Config.default,
    .ulp = modules.ulp_config.Config.default,
    .unity = modules.unity_config.Config.default,
    .usb = modules.usb_config.Config.default,
    .vfs = modules.vfs_config.Config.default,
    .wear_levelling = modules.wear_levelling_config.Config.default,
    .wpa_supplicant = modules.wpa_supplicant_config.Config.default,
    .board = .{
        .name = @as([]const u8, "board.esp32s3_szp"),
        .chip = @as([]const u8, "esp32s3"),
        .target_arch = @as([]const u8, "xtensa"),
        .target_arch_config_flag = @as([]const u8, "CONFIG_IDF_TARGET_ARCH_XTENSA"),
        .target_config_flag = @as([]const u8, "CONFIG_IDF_TARGET_ESP32S3"),
    },
    .partition_table = large_app_partition_table,
};
